# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress

test:
  image: cypress/included:9.5.1
  stage: test
  script:
    - npm install
    # print CI environment variables for reference
    - $(npm bin)/print-env CI
    # run api tests
    - npm run api-test
    # make sure Cypress can run
    - npm run cy:verify
    # run ui tests
    - npm run ui-test
  artifacts:
    paths:
      - cypress/videos
      - cypress/screenshots
    expire_in: 1 day